application: <application_identifier>
version: 000-1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: MySQLdb
  version: "1.2.4b4"

# choose from dev, remote, production
env_variables:
  DJANGO_SETTINGS_MODULE: 'settings.production'

handlers:
- url: /static
  static_dir: production_static

- url: /.*
  script: wsgi.application
